apiVersion: apps.openliberty.io/v1beta2
kind: OpenLibertyApplication
metadata:
  name: openliberty-app-sample
  namespace: defaulte
spec:
  applicationImage: >-
    registry.connect.redhat.com/ibm/open-liberty-samples@sha256:8ea2d3405ff2829d93c5dda4dab5d695ea8ead34e804aaf6e39ea84f53a15ee4
  applicationName: openliberty-app-sample
  expose: true
  pullPolicy: IfNotPresent
  replicas: 1
  resources: {}
  service:
    port: 9080
    type: ClusterIP
